name: Test
on:

  workflow_dispatch:

jobs:
  test:
    name: Test install
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          gpg-private-key: "${{ secrets.GPG_SIGNING_KEY }}"
          overwrite-settings: false
      - name: Build & test core libraries
        run: |
          echo $JAVA_HOME
          ls -l $JAVA_HOME/lib
